name: "AP Infra Pipeline"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform_init_plan:
     runs-on: self-hosted
     env:
        ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        ARM_USE_OIDC: true

     steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          continue-on-error: true

        - name: Terraform Init
          id: init
          run: terraform init -input=false

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color

        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false
          continue-on-error: true

  # terraform_scanning:
  #    runs-on: self-hosted
  #    steps:
  #      - name: Checkout
  #        uses: actions/checkout@v5.0.0

  #      - name: Run Checkov
  #        run: checkov -d .

  terraform_apply:
    runs-on: self-hosted
    needs: [terraform_init_plan]
    if: github.ref == 'refs/heads/main'
    environment: Production
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: .

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: . 

        
        
      
       
