name: "Infra Pipeline"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 78e8a8f8-bd08-4445-a5a6-788de461b87d
          tenant-id: f09cd6a0-7740-4a44-a8a5-c9e688f5f0fc
          subscription-id: 9f199aee-1ad7-464f-bd74-4b88ef990086
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: .
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: .

      

        
        

      
    
    
  
  
    
