name: "Infra Pipeline"

on: workflow_dispatch

jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
    
    
  
  
    
