name: "Dev Terraform Workflow"

on: workflow_dispatch  

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 39f68306-e8d4-4022-b10a-edf212b43929
          tenant-id: 2ba64190-34b7-4c53-a3b5-39b48fc97ee1
          subscription-id: 3848d054-353d-4473-9229-a032df1ddadb
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: .
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: .

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: .        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: .    
