name: "Dev Terraform Workflow"

on: workflow_dispatch  

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      

      
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: .
        

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: .        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: .    
